"""
Project: Blinkit Sales Analysis

Author: Aarush Chugh

Purpose:
This file extracts business insights from the cleaned Blinkit
sales dataset. It identifies top-performing products, outlet
performance, customer ratings, and other key findings that can
support business decision-making.
"""
import pandas as pd
df = pd.read_csv("data/Blinkit-Sales-Analysis-Cleaned.csv")

# Total Sales

print(df["Sales"].sum())

# Average Sales

print(df["Sales"].mean())

# Highest Sales

print(df["Sales"].max())

# Lowest Sales

print(df["Sales"].min())

# Total sales generated by each outlet size

outlet_sales = df.groupby("Outlet Size")["Sales"].sum().sort_values(ascending=False)
print(outlet_sales)

# Total sales by each item category

item_sales = df.groupby("Item Type")["Sales"].sum().sort_values(ascending=False)
print(item_sales)

# Sales by outlet location type

location_sales = df.groupby("Outlet Location Type")["Sales"].sum().sort_values(ascending=False)
print(location_sales)

# Number of products available in each category

item_count = df.groupby("Item Type")["Item Identifier"].count().sort_values(ascending=False)
print(item_count)

# Average customer rating for each item type

average_rating = df.groupby("Item Type")["Rating"].mean().sort_values(ascending=False)
print(average_rating)

#Average Item Weight by Category
weight = (
    df.groupby("Item Type")["Item Weight"]
    .mean()
    .sort_values(ascending=False)
)

print(weight)

#Average Sales by Fat Content
fat_sales = (
    df.groupby("Item Fat Content")["Sales"]
    .mean()
    .sort_values(ascending=False)
)

print(fat_sales)
